"""Generate src/generated/sheets.h from sheets/*.json. One row -> one struct/constant.

Usage: python3 tools/gen.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
S = lambda n: json.load(open(os.path.join(ROOT, "sheets", n + ".json")))
q = lambda s: json.dumps(s)


def rgba(c):
    return "{" + ", ".join(str(x) for x in c) + "}"


def main():
    out = ["// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.",
           "#pragma once", "#include <cstdint>", "#include <cstddef>", ""]

    g = S("guards")["rows"]
    out += ["enum class Guard : std::uint8_t { none = 0, " + ", ".join(f"{r['id']} = {r['code']}" for r in g) + " };",
            "struct GuardRow { Guard id; const char* label; int flickDx; int flickDy; float hudAngleDeg; std::uint8_t color[4]; };",
            "inline constexpr GuardRow kGuards[] = {"]
    out += [f"    {{Guard::{r['id']}, {q(r['label'])}, {r['flick_dx']}, {r['flick_dy']}, {float(r['hud_angle_deg'])}f, {rgba(r['hud_color_rgba'])}}}," for r in g]
    out += ["};", ""]

    out += ["namespace tun {"]
    for r in S("tunables")["rows"]:
        v = r["value"]
        t = "float" if isinstance(v, float) else "int"
        out.append(f"    inline constexpr {t} {r['id']} = {v}{'f' if t == 'float' else ''};  // {r['unit']}: {r['meaning']}")
    out += ["}", ""]

    rules = S("rules")["rows"]
    snd = S("sounds")["rows"]
    out += ["enum class Snd : int { " + ", ".join(r["id"] for r in snd) + ", none = -1 };",
            "struct SoundRow { Snd id; const char* name; const char* pck; const std::uint32_t* wemIds; int wemCount; const char* skyrimMatch; float volume; const char* cacheFile; };"]
    for r in snd:
        ids = r["wem_ids"] or [0]
        out.append(f"inline constexpr std::uint32_t kWem_{r['id']}[] = {{{', '.join(str(x) for x in ids)}}};")
    out += ["inline constexpr SoundRow kSounds[] = {"]
    out += [f"    {{Snd::{r['id']}, {q(r['id'])}, {q(r['fh_pck'])}, kWem_{r['id']}, {len(r['wem_ids'])}, {q(r['skyrim_match'])}, {float(r['volume'])}f, {q(r['cache_file'])}}}," for r in snd]
    out += ["};", ""]

    out += ["enum class Rule : int { " + ", ".join(r["id"] for r in rules) + " };",
            "enum class Cmp : int { any, equal, different };",
            "struct RuleRow { Rule id; Cmp guards; bool victimNotAttacking; bool cancelHit; const char* attackerAnimEvent; Snd sound; };",
            "inline constexpr RuleRow kRules[] = {"]
    for r in rules:
        ev = "nullptr" if r["attacker_anim_event"] == "none" else q(r["attacker_anim_event"])
        out.append(f"    {{Rule::{r['id']}, Cmp::{r['victim_guard_vs_attacker_guard']}, {str(r['requires_victim_not_attacking']).lower()}, "
                   f"{str(r['cancel_hit']).lower()}, {ev}, Snd::{r['sound']}}},")
    out += ["};", ""]

    out += ["namespace hud {",
            "    struct HudRow { const char* id; bool showsPlayer; float anchorX; float anchorY; std::uint8_t active[4]; std::uint8_t idle[4]; };"]
    for r in S("hud")["rows"]:
        out.append(f"    inline constexpr HudRow {r['id']}{{{q(r['id'])}, {str(r['shows'] == 'player').lower()}, {float(r['anchor_x'])}f, {float(r['anchor_y'])}f, "
                   f"{rgba(r['active_color_rgba'])}, {rgba(r['idle_color_rgba'])}}};")
    out += ["}", ""]

    out += ["namespace lay {"]
    for r in S("layouts")["rows"]:
        out.append(f"    inline constexpr std::ptrdiff_t {r['id']} = 0x{r['offset']:X};  // {r['struct']}.{r['field']} ({r['type']})")
    out += ["}", ""]

    ga = S("game_addresses")["rows"]
    versions = next(x for x in S("games")["rows"] if x["role"] == "primary")["versions_supported"]
    out += ["namespace addr {",
            "    enum Id : int { " + ", ".join(r["id"] for r in ga) + ", COUNT };",
            "    enum class Kind : int { data, function, call_site, vtable };",
            "    struct AddrRow { const char* name; Kind kind; int callOffsetHint; int vfuncIndex; };",
            "    inline constexpr AddrRow kRows[COUNT] = {"]
    for r in ga:
        hint = r["call_offset_hint"] if isinstance(r["call_offset_hint"], int) else -1
        vf = r["vfunc_index"] if isinstance(r["vfunc_index"], int) else -1
        out.append(f"        {{{q(r['id'])}, Kind::{r['kind']}, {hint}, {vf}}},")
    out += ["    };",
            "    struct VersionTable { std::uint16_t v[4]; std::uintptr_t off[COUNT]; };",
            "    inline constexpr VersionTable kVersions[] = {"]
    for ver in versions:
        parts = [int(x) for x in ver.split(".")] + [0] * 4
        offs = ", ".join(r["offsets"][ver] for r in ga)
        out.append(f"        {{{{{parts[0]}, {parts[1]}, {parts[2]}, {parts[3]}}}, {{{offs}}}}},")
    out += ["    };", "}", ""]

    os.makedirs(os.path.join(ROOT, "src", "generated"), exist_ok=True)
    open(os.path.join(ROOT, "src", "generated", "sheets.h"), "w").write("\n".join(out))
    print("wrote src/generated/sheets.h")


if __name__ == "__main__":
    main()
